products = [
    {
        "id": 0,
        "name": "Alphonso Mango Devgad",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/329/original/data?1616795305",
        "qty": "6",
        "metric": "pcs",
        "currentPrice": "399",
        "benefits": "- Devgad Alphanso mangoes are naturally grown in the Devgad district of Maharashtra region of India. - Devgad Alphonso has a stronger and thicker coat. Hence, they’re less prone to getting wrinkles. - \"Alphonso\" originated from a Portuguese general’s name 'Afonso de Albuquerque'. - Alphonso mango is a very costly variety of fruit in the world also know for best in taste and aroma fruit.",
        "info": "- Alphanso mango also very healthy highly contains vitamins like Vitamin E, Vitamin A, Carotene and minerals like Magnesium, Manganese, Phosphorus. - Did you know it helps to regulating cholestrol levels in body and digestion process by adding mango in your diet during summer season. It can be used in dried form as well and used as part of salads. - It is also season best fruit to increases eye sight, prevents night blindness and dry eyes health issues.",
        "category": "mangoes",
        "oldPrice": "456"
    },
    {
        "id": 1,
        "name": "Mango Badami",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/135/original/data?1612689931",
        "qty": "1",
        "metric": "kg",
        "currentPrice": "88",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "mangoes"
    },
    {
        "id": 2,
        "name": "Mango Totapuri Raw",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/images/images/000/004/597/original/data?1647577454",
        "qty": "1",
        "metric": "kg",
        "currentPrice": "56",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "mangoes"
    },
    {
        "id": 3,
        "name": "Mango Lalbhag Sindhura",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/250/original/data?1621065378",
        "qty": "1",
        "metric": "kg",
        "currentPrice": "134",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "mangoes"
    },
    {
        "id": 4,
        "name": "Mango Raw",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VMAN12.png",
        "qty": "250",
        "metric": "g",
        "currentPrice": "12",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "mangoes"
    },
    {
        "id": 5,
        "name": "Mango Kesar",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/FKES1.png",
        "qty": "1",
        "metric": "kg",
        "currentPrice": "249",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "mangoes"
    },
    {
        "id": 6,
        "name": "Alphonso Mango Devgad (2 x 6 pcs)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/339/original/data?1620237313",
        "qty": "12",
        "metric": "pcs",
        "currentPrice": "899",
        "benefits": "- Devgad Alphanso mangoes are naturally grown in the Devgad district of Maharashtra region of India. आम की लगभग 100 से भी ज्यादा किस्में पाई जाती हैं। - Devgad Alphonso has a stronger and thicker coat. Hence, they’re less prone to getting wrinkles. - \"Alphonso\" originated from a Portuguese general’s name 'Afonso de Albuquerque'. - Alphonso mango is a very costly variety of fruit in the world also know for best in taste and aroma fruit. आम कई रंगों में आते हैं जैसे – हरा, लाल, पीला आदि। इतना ही नहीं, आम अलग-अलग आकार के भी होते हैं।",
        "info": "- Alphanso mango available in Dozen and in Pieces; it is also very healthy highly contains vitamins like Vitamin E, Vitamin A, Carotene and minerals like Magnesium, Manganese, Phosphorus. Alphanso mango . आम जब थोड़ा कच्चा रहता है, तो उसमें विटामिन-सी की मात्रा ज्यादा होती है। वहीं, जब यह पक जाता है, तो इसमें विटामिन-ए की मात्रा अधिक हो जाती है। - Did you know it helps to regulating cholesterol levels in body and digestion process by adding mango in your diet during summer season. It can be used in dried form as well and used as part of salads. - It is also season best fruit to increases eye sight, prevents night blindness and dry eyes health issues.",
        "category": "mangoes",
        "oldPrice": "1199"
    },
    {
        "id": 7,
        "name": "Mango Mallika",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/images/images/000/007/294/original/data?1650906368",
        "qty": "1",
        "metric": "kg",
        "currentPrice": "149",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "mangoes"
    },
    {
        "id": 8,
        "name": "Apple Royal Gala",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/006/original/data?1642616267",
        "qty": "4",
        "metric": "pcs",
        "currentPrice": "99",
        "benefits": "- In Apple, Vitamin C and dietary fiber are high in this fruit, which helps to maintain the health of our digestive and immune systems. - One of the healthiest fruits is the apple. - Obesity is reduced by eating apple peel.",
        "info": "- Apple royal gala is one of variety of apple category are in red color and sweet. - The Royal Gala apple, as its name suggests, is regal in appearance, with gorgeous golden streaks. - Obesity-related inflammation, which is linked to an elevated risk of heart disease, was lowered by eating Gala apples on a daily basis. - Gala apples have a thin, yellow-orange peel with a little red tinge. Their flesh has a moderate sweet flavor and is dense, crisp, and creamy yellow in color. -Galas are often taller than wide in shape.",
        "category": "fruits",
        "oldPrice": "125"
    },
    {
        "id": 9,
        "name": "Wood Apple",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/244/original/data?1613050070",
        "qty": "1",
        "metric": "pcs",
        "currentPrice": "18",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "fruits"
    },
    {
        "id": 10,
        "name": "Pear Green / Packham",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/096/original/data?1625415915",
        "qty": "500",
        "metric": "g",
        "currentPrice": "122",
        "benefits": "- Green pears are abundant in nutrients and include dietary fiber, including prebiotics, which help to maintain bowel regularity, relieve constipation, and improve overall digestive health. - Eat your Green pear with the skin on to get the most fiber from it. - Green pears also help to reduce your risk of type 2 diabetes due to their fiber and anthocyanin contents.",
        "info": "- Pear green are recognizable for their egg-shaped appearance, having a larger spherical lower portion that begins a gradual taper above the mid-point to a narrower rounded top. - Their skin color is bright green, and sometimes has a soft red blush. - Pears are sweet, bell-shaped fruits have been around since the start of time. This fruit available in two varieties crisp and soft.",
        "category": "fruits"
    },
    {
        "id": 11,
        "name": "Apple Red Delicious",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/241/original/data?1610967581",
        "qty": "4",
        "metric": "pcs",
        "currentPrice": "119",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "fruits",
        "oldPrice": "176"
    },
    {
        "id": 12,
        "name": "Apple Green / Granny Smith",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/FAPP23.png",
        "qty": "4",
        "metric": "pcs",
        "currentPrice": "255",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "fruits"
    },
    {
        "id": 13,
        "name": "Pumpkin Green",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/101/original/data?1612451098",
        "qty": "500",
        "metric": "g",
        "currentPrice": "11",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables",
        "oldPrice": "16"
    },
    {
        "id": 14,
        "name": "Capsicum (Shimla), Green Shimla Mirchi",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VCAP12.png",
        "qty": "250",
        "metric": "g",
        "currentPrice": "13",
        "benefits": "- Capsicum helps you burn fat and lose weight. The capsicum veggie also improves digestion. - Capsicum lowers the risk of cancer as it contains anti-inflammatory nutrients and antioxidants. - Capsicum includes a chemical called capsaicin, which is thought to prevent pain from reaching the spinal cord. It is beneficial in the treatment of herpes zoster and neuralgia pain. It helps to alleviate discomfort.",
        "info": "- Capsicum has a low fat level, as well as a high fiber and water content.",
        "category": "vegetables"
    },
    {
        "id": 15,
        "name": "Cucumber Green Indian / Kheera / Kakdi",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/315/original/data?1614700255",
        "qty": "500",
        "metric": "g",
        "currentPrice": "18",
        "benefits": "- Cucumbers are low in calories and high in water and soluble fiber, making it a great choice for encouraging hydration and fat loss. खीरा में विटामिन सी, बीटा कैरोटीन जैसे एंटी ऑक्सीडेंट्स पाए जाते हैं. जिससे शरीर में मौजूद फ्री रेडिकल्स दूर होते हैं - Cucumber peel reversed most of the diabetes-associated changes and caused a decrease in blood sugar. - Cucumber is known for its anti-cancer properties and reduces risk of cancer spread in your body.",
        "info": "- Cucumbers can be used as essential to bring freshness and taste to salads, sandwiches, and side dishes, as well as to replace more calorie options. - Cucumbers are high in water and promote hydration. - Cucumbers can be eaten fresh or pickled. They can be enjoyed as a low-calorie snack or used to add flavor in a variety of dishes.",
        "category": "vegetables"
    },
    {
        "id": 16,
        "name": "Brinjal Bharta",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VBRI12.png",
        "qty": "500",
        "metric": "g",
        "currentPrice": "17",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables",
        "oldPrice": "24"
    },
    {
        "id": 17,
        "name": "Cabbage",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VCAB12.png",
        "qty": "1",
        "metric": "pcs",
        "currentPrice": "6",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables",
        "oldPrice": "10"
    },
    {
        "id": 18,
        "name": "Cauliflower",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VCAU12.png",
        "qty": "1",
        "metric": "pcs",
        "currentPrice": "38",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables"
    },
    {
        "id": 19,
        "name": "Bitter Gourd (Karela)",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VBIT12.png",
        "qty": "500",
        "metric": "g",
        "currentPrice": "23",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables"
    },
    {
        "id": 20,
        "name": "Pumpkin Red",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VPUM12.png",
        "qty": "500",
        "metric": "g",
        "currentPrice": "42",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables"
    },
    {
        "id": 21,
        "name": "Bottle Gourd (Dudhi / Lauki)",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VBOT12.png",
        "qty": "1",
        "metric": "pcs",
        "currentPrice": "8",
        "benefits": "Bottle Gourd Nutrition - Has zero fat & cholesterol content - Good source of Vitamin C & minerals like potassium, calcium & sodium - Rich in fibre Bottle Gourd Health Benefits - Helps in weight loss - Treats UTI - Cools our body, so usually preferred after a workout - Keeps our heart healthy & relieves stress",
        "info": "Bottle gourds can be sauted, fried, grilled, or converted into pickles. It can also be prepared as curry or used to make delicacies. Some famous Indian dishes with bottle gourd are Sorakkai Poriyal, Lauki kofta, Lauki thepla, Lauki Sabzi, Lauki Halwa, Lauki Paratha, & more. Did you know? - Bottle gourd belongs to the pumpkin family.",
        "category": "vegetables",
        "oldPrice": "10"
    },
    {
        "id": 22,
        "name": "Brinjal Kateri, Baingan",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/028/original/data?1616765740",
        "qty": "250",
        "metric": "g",
        "currentPrice": "14",
        "benefits": "- Kateri Brinjals are rich in fiber and polyphenols, making them a good choice for controlling blood sugar and for diabetics.",
        "info": "- Brinjals are cousins of potatoes, tomatoes, and bell peppers and belong to the Family Solanaceae, also known as nightshades. - Brinjals of this kind are small and oval in shape, and are often consumed in Indian households. - This type of brinjal is small and oval in shape, and it is commonly consumed in Indian households; commonly used to make Indian curries.",
        "category": "vegetables"
    },
    {
        "id": 23,
        "name": "Drumstick",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VDRU12.png",
        "qty": "100",
        "metric": "g",
        "currentPrice": "7",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables"
    },
    {
        "id": 24,
        "name": "Snake Gourd (Bada Parwal)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/106/original/data?1603884029",
        "qty": "250",
        "metric": "g",
        "currentPrice": "16",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables"
    },
    {
        "id": 25,
        "name": "Cucumber White",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/316/original/data?1614700848",
        "qty": "500",
        "metric": "g",
        "currentPrice": "14",
        "benefits": "Cucumbers have a minimal calorie, carbohydrate, salt, fat, and cholesterol content due to their natural composition. Not only are white cucumbers high in water, but they also include key nutrients like magnesium and potassium that aid in hydration. Cucumbers white contain anti-inflammatory compounds that help in the removal of waste and reduce skin damage and irritation.",
        "info": "Cucumber is a very healthy and versatile vegetable. Cucumber White Wonder can thrive outside of a greenhouse on a sunny and sheltered plot. Cucumber works well with lettuce, sweet pepper, cheese, apple, carrot, mint, chives, potatoes, radishes, onion, rice, pasta and almonds to name a few.",
        "category": "vegetables",
        "oldPrice": "23"
    },
    {
        "id": 26,
        "name": "Brinjal Black / Nagpur",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VBRI22.png",
        "qty": "500",
        "metric": "g",
        "currentPrice": "16",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables",
        "oldPrice": "24"
    },
    {
        "id": 27,
        "name": "Ash Gourd (White Pumpkin)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/164/original/data?1629975839",
        "qty": "500",
        "metric": "g",
        "currentPrice": "29",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables"
    },
    {
        "id": 28,
        "name": "Ridge Gourd (Turai) ",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/images/images/000/006/625/original/data?1649244316",
        "qty": "500",
        "metric": "g",
        "currentPrice": "26",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables"
    },
    {
        "id": 29,
        "name": "Beans Cluster (Gavar)",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VGAV12.png",
        "qty": "250",
        "metric": "g",
        "currentPrice": "18",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables"
    },
    {
        "id": 30,
        "name": "Tondli",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VTON12.png",
        "qty": "500",
        "metric": "g",
        "currentPrice": "24",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables",
        "oldPrice": "33"
    },
    {
        "id": 31,
        "name": "Beans French",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VFRE12.png",
        "qty": "500",
        "metric": "g",
        "currentPrice": "108",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables"
    },
    {
        "id": 32,
        "name": "Beans Chawli",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VCHA12.png",
        "qty": "250",
        "metric": "g",
        "currentPrice": "19",
        "benefits": "Green Chawli beans increases the platelet count and helps in relieving itching and dryness. Vitamin A, folic acid, calcium, and other vitamins like vitamin K, thiamin, niacin, vitamin B-6, and vitamin E are all high in green Chawli beans. It also has a substantial amount of chlorophyll and iron.",
        "info": "Green Chawli long beans are a sort of green vegetable that is accessible all year. It's 12 to 30 inches in length, slender, and vary in colour from light green to dark green, depending on the cultivar. Long beans are used in Indian cookery to produce sabzi, salad, and paratha stuffing. Stir fries are also made with them in Chinese and Malaysian cuisines.",
        "category": "vegetables"
    },
    {
        "id": 33,
        "name": "Sponge Gourd (Galka)",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VSPO12.png",
        "qty": "500",
        "metric": "g",
        "currentPrice": "23",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables"
    },
    {
        "id": 34,
        "name": "Tinda",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VTIN12.png",
        "qty": "250",
        "metric": "g",
        "currentPrice": "28",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "vegetables"
    },
    {
        "id": 35,
        "name": "Lady's Finger (Bhindi / Okra / Bhendi)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/images/images/000/006/624/original/data?1649243792",
        "qty": "500",
        "metric": "g",
        "currentPrice": "16",
        "benefits": "- Bhindi is high in fiber, which aids with diabetes management. - Okra/ Bhindi is strong in vitamin C, which has been shown to increase immunity and protect against common diseases. - Bhindi is abundant in insoluble dietary fiber, which aids in the cleansing of the entire digestive system, particularly the intestines.",
        "info": "- The lady's finger may be cut in to round pieces or sliced in to 4 halves stickiness. - Lady finger benefits for eyes; it has a good amounts of carotenoids that improve and maintain vision. - स्वाद में लाजवाब हरे रंग की भिंडी के औषधीय गुण कई हैं। - भिंडी के सेवन ब्लड शुगर लेवल तेजी से नहीं बढ़ता है| - भिंडी से पाया जाने वाला फाइबर रक्त के ग्लूकोज को नियंत्रित करने में फायदेमंद हो सकता है|",
        "category": "vegetables"
    },
    {
        "id": 36,
        "name": "Betel Leaf - 12 Pcs",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/602/original/data?1635155510",
        "qty": "12",
        "metric": "pcs",
        "currentPrice": "30",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 37,
        "name": "Lemon(100g) / Nimboo / Nibu",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/003/250/original/data?1642167498",
        "qty": "100",
        "metric": "g",
        "currentPrice": "19",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs",
        "oldPrice": "26"
    },
    {
        "id": 38,
        "name": "Special Offer Coriander",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/003/163/original/data?1640321543",
        "qty": "30",
        "metric": "g",
        "currentPrice": "4",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs",
        "oldPrice": "13"
    },
    {
        "id": 39,
        "name": "Masala Combo",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/003/276/original/data?1642317197",
        "qty": "100",
        "metric": "g",
        "currentPrice": "34",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs",
        "oldPrice": "43"
    },
    {
        "id": 40,
        "name": "Colocasia Leaves",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/419/original/data?1635147438",
        "qty": "1",
        "metric": "pcs",
        "currentPrice": "2",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 41,
        "name": "Ginger / Adrak",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VGIN12.png",
        "qty": "100",
        "metric": "g",
        "currentPrice": "6",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 42,
        "name": "Curry Leaves",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/LCUR11.png",
        "qty": "50",
        "metric": "g",
        "currentPrice": "10",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 43,
        "name": "Chillies Green",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VCHI22.png",
        "qty": "100",
        "metric": "g",
        "currentPrice": "12",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 44,
        "name": "Garlic Peeled",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VGAR32.png",
        "qty": "100",
        "metric": "g",
        "currentPrice": "33",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 45,
        "name": "Garlic Bunch / Lahsun / Vellulipaya",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VGAR12.png",
        "qty": "100",
        "metric": "g",
        "currentPrice": "10",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 46,
        "name": "Coriander Leaves / Dhania / Kothimbir",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/LCOR21.png",
        "qty": "100",
        "metric": "g",
        "currentPrice": "13",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 47,
        "name": "Methi (Fenugreek Leaves)",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/LMET1.png",
        "qty": "100",
        "metric": "g",
        "currentPrice": "17",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 48,
        "name": "Palak Spinach",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/LSPI11.png",
        "qty": "250",
        "metric": "g",
        "currentPrice": "25",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 49,
        "name": "Turmeric",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/375/original/data?1623816989",
        "qty": "250",
        "metric": "g",
        "currentPrice": "18",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 50,
        "name": "Amla",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VAWL11.png",
        "qty": "250",
        "metric": "g",
        "currentPrice": "42",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 51,
        "name": "Aloevera",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/417/original/data?1628778604",
        "qty": "1",
        "metric": "pcs",
        "currentPrice": "13",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 52,
        "name": "Banana Stem",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/380/original/data?1635063619",
        "qty": "1",
        "metric": "pcs",
        "currentPrice": "17",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 53,
        "name": "Amaranthus Red",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/162/original/data?1598301503",
        "qty": "250",
        "metric": "g",
        "currentPrice": "16",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs",
        "oldPrice": "27"
    },
    {
        "id": 54,
        "name": "Mint Leaves / Pudina",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/LMIN11.png",
        "qty": "100",
        "metric": "g",
        "currentPrice": "7",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 55,
        "name": "Spring Onion",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/LSPR11.png",
        "qty": "250",
        "metric": "g",
        "currentPrice": "20",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "herbs"
    },
    {
        "id": 56,
        "name": "Cashew & Kismis Combo Pack (Cashew 100gm + Kismis 200gm)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/003/263/original/data?1642176073",
        "qty": "300",
        "metric": "g",
        "currentPrice": "149",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "dry fruits",
        "oldPrice": "246"
    },
    {
        "id": 57,
        "name": "Cashew 500gms (Pack of 5*100gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/579/original/data?1635086198",
        "qty": "500",
        "metric": "g",
        "currentPrice": "450",
        "benefits": "Cashews are low in sugar and rich in fiber, heart-healthy fats, and plant protein. They're also a good source of copper, magnesium, and manganese",
        "info": "\"Premium Cashews Quantity 500 g Pack of 5",
        "category": "dry fruits",
        "oldPrice": "830"
    },
    {
        "id": 58,
        "name": "Cashew 200gms (Pack of 2*100gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/578/original/data?1635085993",
        "qty": "200",
        "metric": "g",
        "currentPrice": "182",
        "benefits": "Cashews are low in sugar and rich in fiber, heart-healthy fats, and plant protein. They're also a good source of copper, magnesium, and manganese",
        "info": "\"Premium Cashews Quantity 200 g Pack of 2",
        "category": "dry fruits",
        "oldPrice": "332"
    },
    {
        "id": 59,
        "name": "Walnut 200gms (Pack of 2*100gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/584/original/data?1635137208",
        "qty": "200",
        "metric": "g",
        "currentPrice": "335",
        "benefits": "Walnuts are rich in heart-healthy fats and high in antioxidants.",
        "info": "Ingedients- Walnuts Quantity- 200g(Pack of 2)",
        "category": "dry fruits",
        "oldPrice": "478"
    },
    {
        "id": 60,
        "name": "Dry Dates - 200gms",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/596/original/data?1635146122",
        "qty": "200",
        "metric": "g",
        "currentPrice": "70",
        "benefits": "Dried dates are a great source of fiber and also include several important vitamins and minerals.",
        "info": "Premium Dry Dates Quantity- 200g",
        "category": "dry fruits",
        "oldPrice": "92"
    },
    {
        "id": 61,
        "name": "Cashew Tukda - 100gm",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/580/original/data?1635086672",
        "qty": "100",
        "metric": "g",
        "currentPrice": "84",
        "benefits": "Cashews are low in sugar and rich in fiber, heart-healthy fats, and plant protein. They're also a good source of copper, magnesium, and manganese",
        "info": "Premium Cashews (Tukda) Quantity 100 g",
        "category": "dry fruits",
        "oldPrice": "118"
    },
    {
        "id": 62,
        "name": "Almond - 100gms",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/590/original/data?1635143515",
        "qty": "100",
        "metric": "g",
        "currentPrice": "115",
        "benefits": "Almonds have always proved beneficial as it lowers blood sugar levels, reduced blood pressure and lower cholesterol levels. They can also reduce hunger and promote weight loss.",
        "info": "Premium Almonds Quantity- 200g",
        "category": "dry fruits",
        "oldPrice": "136"
    },
    {
        "id": 63,
        "name": "Walnut - 100gms",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/583/original/data?1635137039",
        "qty": "100",
        "metric": "g",
        "currentPrice": "175",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "dry fruits",
        "oldPrice": "239"
    },
    {
        "id": 64,
        "name": "Cashew - 100gm",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/577/original/data?1635085485",
        "qty": "100",
        "metric": "g",
        "currentPrice": "104",
        "benefits": "Cashews are low in sugar and rich in fiber, heart-healthy fats, and plant protein. They're also a good source of copper, magnesium, and manganese",
        "info": "Premium Cashews Quantity 100 g",
        "category": "dry fruits",
        "oldPrice": "166"
    },
    {
        "id": 65,
        "name": "Kismis - 200 gms",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/593/original/data?1635144647",
        "qty": "200",
        "metric": "g",
        "currentPrice": "59",
        "benefits": "Raisins are a rich source of fiber, iron, calcium, potassium, and other essential nutrients, that provide you with an energy boost and help you keep your hair and skin glowing.",
        "info": "Premium Raisins(Kismis) Quantity- 200g",
        "category": "dry fruits",
        "oldPrice": "80"
    },
    {
        "id": 66,
        "name": "Almond 200gms (Pack of 2*100gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/591/original/data?1635143661",
        "qty": "200",
        "metric": "g",
        "currentPrice": "206",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "dry fruits",
        "oldPrice": "272"
    },
    {
        "id": 67,
        "name": "Walnut 500gms (Pack of 5*100gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/585/original/data?1635137356",
        "qty": "500",
        "metric": "g",
        "currentPrice": "825",
        "benefits": "Walnuts are rich in heart-healthy fats and high in antioxidants.",
        "info": "\"ngedients- Walnuts Quantity- 500g(Pack of 5)",
        "category": "dry fruits",
        "oldPrice": "1195"
    },
    {
        "id": 68,
        "name": "Kismis - 1 Kg (Pack of 5*200 gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/595/original/data?1635145018",
        "qty": "1",
        "metric": "kg",
        "currentPrice": "289",
        "benefits": "Raisins contain iron, which benefits cardiovascular health. They have calcium, which benefits bone health. Raisins have small amounts of protein. Raisins are a good source of fiber.",
        "info": "Ingredient-Raisins Quantity - 1 Kg Quality- Best",
        "category": "dry fruits",
        "oldPrice": "400"
    },
    {
        "id": 69,
        "name": "Dry Dates - 1 Kg (Pack of 5*200 gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/598/original/data?1635146504",
        "qty": "1",
        "metric": "kg",
        "currentPrice": "330",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "dry fruits",
        "oldPrice": "460"
    },
    {
        "id": 70,
        "name": "Dry Dates - 400gms (Pack of 2*200gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/597/original/data?1635146300",
        "qty": "400",
        "metric": "g",
        "currentPrice": "135",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "dry fruits",
        "oldPrice": "184"
    },
    {
        "id": 71,
        "name": "Kismis - 400 gms (Pack of 2*200 gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/594/original/data?1635144809",
        "qty": "400",
        "metric": "g",
        "currentPrice": "116",
        "benefits": "Raisins contain iron, which benefits cardiovascular health. They have calcium, which benefits bone health. Raisins have small amounts of protein. Raisins are a good source of fiber.",
        "info": "Ingredient-Raisins Quantity - 200 Kg Pack of 2",
        "category": "dry fruits",
        "oldPrice": "160"
    },
    {
        "id": 72,
        "name": "Pista Kernel - 100gms",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/588/original/data?1635142184",
        "qty": "100",
        "metric": "g",
        "currentPrice": "175",
        "benefits": "Pistachios are not only a good source of garnishing sweets but also make up as one of the healthiest foods. They are nutrition pack powerhouses loaded with antioxidants including, lutein, beta-carotene and gamma-tocopherol. They prevent cell damage that may reduce the risk of diseases.",
        "info": "Premium Salted Kernel Quantity- 100g",
        "category": "dry fruits",
        "oldPrice": "242"
    },
    {
        "id": 73,
        "name": "Almond 500gms (Pack of 5*100gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/592/original/data?1635143799",
        "qty": "500",
        "metric": "g",
        "currentPrice": "489",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "dry fruits",
        "oldPrice": "680"
    },
    {
        "id": 74,
        "name": "Cashew Tukda 200gms (Pack of 2*100gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/581/original/data?1635086887",
        "qty": "200",
        "metric": "g",
        "currentPrice": "167",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "dry fruits",
        "oldPrice": "236"
    },
    {
        "id": 75,
        "name": "Pista Salted - 100gms",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/586/original/data?1635141850",
        "qty": "100",
        "metric": "g",
        "currentPrice": "115",
        "benefits": "Pistachios are not only a good source of garnishing sweets but also make up as one of the healthiest foods. They are nutrition pack powerhouses loaded with antioxidants including, lutein, beta-carotene and gamma-tocopherol. They prevent cell damage that may reduce the risk of diseases.",
        "info": "Premium Salted Pista Quantity- 100g",
        "category": "dry fruits",
        "oldPrice": "167"
    },
    {
        "id": 76,
        "name": "Pista Kernel 200gms (Pack of 2*100gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/589/original/data?1635142329",
        "qty": "200",
        "metric": "g",
        "currentPrice": "345",
        "benefits": "Pistachios are not only a good source of garnishing sweets but also make up as one of the healthiest foods. They are nutrition pack powerhouses loaded with antioxidants including, lutein, beta-carotene and gamma-tocopherol. They prevent cell damage that may reduce the risk of diseases.",
        "info": "Premium Kernel Quantity- 200g Pack of 2",
        "category": "dry fruits",
        "oldPrice": "484"
    },
    {
        "id": 77,
        "name": "Pista Salted 200gms (Pack of 2*100gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/587/original/data?1635142002",
        "qty": "200",
        "metric": "g",
        "currentPrice": "229",
        "benefits": "Pistachios are not only a good source of garnishing sweets but also make up as one of the healthiest foods. They are nutrition pack powerhouses loaded with antioxidants including, lutein, beta-carotene and gamma-tocopherol. They prevent cell damage that may reduce the risk of diseases.",
        "info": "Premium Salted Quantity- 200g Pack of 2",
        "category": "dry fruits",
        "oldPrice": "334"
    },
    {
        "id": 78,
        "name": "Cashew Tukda 500gms (Pack of 5*100gms)",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/582/original/data?1635086999",
        "qty": "500",
        "metric": "g",
        "currentPrice": "415",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "dry fruits",
        "oldPrice": "590"
    },
    {
        "id": 79,
        "name": "Dates Kimia",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/159/original/data?1595448691",
        "qty": "500",
        "metric": "g",
        "currentPrice": "226",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "dry fruits"
    },
    {
        "id": 80,
        "name": "Maya Whole Spice Black Cardamom, 50 g",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/images/images/000/007/120/original/data?1649657414",
        "qty": "50",
        "metric": "g",
        "currentPrice": "66",
        "benefits": "Enhance the taste of your food Naturally healthy and tasty Beautiful aroma and taste",
        "info": "Brand - Maya Form - Whole Quantity - 50 g",
        "category": "kitchen staples",
        "oldPrice": "97"
    },
    {
        "id": 81,
        "name": "Maya Whole Spice Big Mustard Seeds, 100 g",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/images/images/000/005/382/original/data?1648552884",
        "qty": "100",
        "metric": "g",
        "currentPrice": "17",
        "benefits": "Maya Rai Whole is an essential part of Indian spice that goes in variety of Indian dishes and makes it even more flavourful, aromatic, and tasty. Its intense aroma and richness in flavour that enhances the taste of Indian cuisines. Mustard seeds have high oil and protein content. Mustard seeds have a beneficial chemical composition such as its protein content and fairly well-balanced amino acid composition, rich in dietary fiber and natural antioxidants.",
        "info": "Brand - Maya Form - Whole Quantity - 100 g",
        "category": "kitchen staples",
        "oldPrice": "19"
    },
    {
        "id": 82,
        "name": "Maya Whole Spice Coriander 100G",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/003/468/original/data?1643128069",
        "qty": "100",
        "metric": "g",
        "currentPrice": "30",
        "benefits": "Perfectly balanced in aroma and flavour Rich in vitamin c and vitamin k Source of dietary fiber, manganese, iron and magnesium",
        "info": "Brand - Maya Quantity - 100 g Form - Whole",
        "category": "kitchen staples",
        "oldPrice": "32"
    },
    {
        "id": 83,
        "name": "Maya Whole Spice Shahi Jeera 50G",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/003/477/original/data?1643128090",
        "qty": "50",
        "metric": "g",
        "currentPrice": "42",
        "benefits": "This spice has antioxidant properties Reduces the inflammation Has amazing glucose-lowering effects Very good to control appetite Ideal for weight maintenance",
        "info": "Brand- Maya Type- Shahi Jeera Quantity- 50 gms Essential spice of India",
        "category": "kitchen staples",
        "oldPrice": "43"
    },
    {
        "id": 84,
        "name": "Maya Whole Spice Garam Masala, 100 g",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/images/images/000/007/119/original/data?1649657173",
        "qty": "100",
        "metric": "g",
        "currentPrice": "71",
        "benefits": "Improves the Immune system. Garam Masala can be used to cook the seasoning of various Indian dishes including meat, vegetables, dal, seasoned yogurt and curries. This concoction releases a dose of layered taste and gives the dish a slightly spicy edge. Helps the digestive system.",
        "info": "Brand - Maya Form - Whole Quantity - 100 g",
        "category": "kitchen staples",
        "oldPrice": "89"
    },
    {
        "id": 85,
        "name": "Maya Whole Spice Guntur Chilli 100g",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/images/images/000/005/081/original/data?1648280317",
        "qty": "100",
        "metric": "g",
        "currentPrice": "40",
        "benefits": "Guntur chilli has many nutritional benefits like high source of vitamin C content, beta-carotene. They help in weight loss, muscle pain relief. Chilli has very High Pungency & Heat and a typical tangy flavour.",
        "info": "Brand - Maya Form - Whole Quantity - 100 g",
        "category": "kitchen staples",
        "oldPrice": "45"
    },
    {
        "id": 86,
        "name": "Maya Whole Spice Mustard Small 100G",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/003/475/original/data?1643128085",
        "qty": "100",
        "metric": "g",
        "currentPrice": "17",
        "benefits": "Maya Rai Whole is an essential part of Indian spice that goes in variety of Indian dishes and makes it even more flavourful, aromatic, and tasty. Its intense aroma and richness in flavour that enhances the taste of Indian cuisines. Mustard seeds have high oil and protein content. Mustard seeds have a beneficial chemical composition such as its protein content and fairly well-balanced amino acid composition, rich in dietary fiber and natural antioxidants.",
        "info": "Brand - Maya Form - Whole (small) Quantity - 100 g",
        "category": "kitchen staples",
        "oldPrice": "20"
    },
    {
        "id": 87,
        "name": "Banana Robusta",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/FBAN14.png",
        "qty": "1",
        "metric": "kg",
        "currentPrice": "25",
        "benefits": "Banana Health Benefits - Helps with digestion & gastrointestinal issues - heartburn, ulcers, constipation - Banana has potassium, which helps in maintaining good heart health & blood pressure - Helps in regulating mood & good for brain health - Makes us feel fuller & helps in improving kidney health Banana Nutrition - Great source of Vitamin B6 & C - Source of minerals like manganese, potassium, folate - Low on Fat, Cholesterol & Sodium - Contains dietary fiber\n",
        "info": "- The best way to ripen the bananas is to keep it with other fruits in a bowl at room temperature. - One can store bananas in the fridge once they ripen. - Ripe Banana Recipes include Banana Smoothies, Banana Bread, Banana Pancakes, Banana Cake, Banana muffins, & more. - Some regional recipes like Pazham pori, Banana appam, Mangalore buns, Banana sheera, Banana rasayana & more. Did you know? - Bananas usually float on water as they are less dense. - Banana is classified as berry\n",
        "category": "fruits",
        "oldPrice": "37"
    },
    {
        "id": 88,
        "name": "Coconut Tender / Nariyal Pani",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/257/original/data?1612448669",
        "qty": "1",
        "metric": "pcs",
        "currentPrice": "33",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "fruits",
        "oldPrice": "38"
    },
    {
        "id": 89,
        "name": "Blueberry",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/FBLU1.png",
        "qty": "20",
        "metric": "pcs",
        "currentPrice": "229",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "fruits",
        "oldPrice": "294"
    },
    {
        "id": 90,
        "name": "Chikoo",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/FCHI13.png",
        "qty": "500",
        "metric": "g",
        "currentPrice": "22",
        "benefits": "Chikoo is a high calorie fruit with an abundant source of fibers and vitamin A and vitamin C that help to build immunity and skin health.\n",
        "info": "Chikoo/ Sapota is a delicious calorie-rich fruit belonging to the category of fruits like mango. This fruit is better known as Chikoo in India. Sapota or chikoo is an oval or round shape fruit with brown skin. The unripe fruit has a hard surface and white pulp due to its high content of latex. The latex content reduces as the fruit ripens and its flesh acquires a brown colour. The flesh contains black, shiny bean-like seeds in the center.\n",
        "category": "fruits",
        "oldPrice": "32"
    },
    {
        "id": 91,
        "name": "Coconut",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/FCOC1.png",
        "qty": "1",
        "metric": "pcs",
        "currentPrice": "24",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "fruits"
    },
    {
        "id": 92,
        "name": "Dragon Fruit",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/FDRA1.png",
        "qty": "1",
        "metric": "pcs",
        "currentPrice": "135",
        "benefits": "- Dragon fruit contains vitamin C helps to improve skin radiance; also it make your skin glowing, if you make dragon fruit juice and drink it once a day. - It is naturally fat free and high in fiber. - It helps to lower your blood sugar. - Dragon fruit contains probiotics which can kill disease-causing viruses and bacteria and also help to improve digestion of food",
        "info": "-Dragon fruit is also known as Pitaya, or strawberry pear. -It's a cactus that produces a tropical fruit. It's accessible from everywhere on the planet. -Such a well variety of dragon fruit has pink skin and white meat, although it is the least sweet. -Peel and cut it into sections when you’re ready to eat it. Much like an avocado, you eat the flesh and discard the skin. You could also cut it in half and scoop out the flesh with a spoon or melon baller.",
        "category": "fruits"
    },
    {
        "id": 93,
        "name": "Grapes Green",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/FGRA42.png",
        "qty": "500",
        "metric": "g",
        "currentPrice": "49",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "fruits"
    },
    {
        "id": 94,
        "name": "Mosambi",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/FMOS13.png",
        "qty": "1",
        "metric": "kg",
        "currentPrice": "84",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "fruits"
    },
    {
        "id": 95,
        "name": "Musk Melon/ Kharabooja",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/FMUS1.png",
        "qty": "1",
        "metric": "pcs",
        "currentPrice": "21",
        "benefits": "Musk melons are cooling and help in constipation, bladder infections, ulcers, fatigue, colitis, and blood pressure.\n",
        "info": "Musk melons (Kharbuja) sabzi quick simple and easy to make. Muskmelons, also known as sweet melon, kharbuja, and cantaloupe, are a member of the Cucurbitaceae family and therefore are botanically known as Cucumis melo. A strong \"muskmelon\" pleasant aroma is produced by a ripe melon.\n",
        "category": "fruits",
        "oldPrice": "30"
    },
    {
        "id": 96,
        "name": "Papaya",
        "image": "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/092/original/data?1620114635",
        "qty": "1",
        "metric": "pcs",
        "currentPrice": "29",
        "benefits": "Papaya Health Benefits - The antioxidants like carotenoids helps in reducing the risk of cardiovascular diseases - High fiber in papaya helps in lowering cholesterol - Papaya has lycopene which helps in reducing the risk of cancer - Papaya skin is used for facial treatments - for glowing skin Papaya Nutrition - Contains a high level of antioxidants which helps in preventing the oxidation of cholesterol. - A good source of fiber - Has vitamins A, vitamin C & vitamin E\n",
        "info": "- Papaya ripens quickly when wrapped in a newspaper. - Or one can also place papaya near some bananas to ripen the papayas quickly. - Once the papaya is ripe, one can cut it & remove the seeds and then store it in the refrigerator. - Must try Papaya Recipes include Papite ka halwa or Papaya Halwa, Papaya Salad, Papaya Badam Barfi, & more. Did you know? - Papaya is actually a big berry.\n",
        "category": "fruits",
        "oldPrice": "38"
    },
    {
        "id": 97,
        "name": "Papaya Raw",
        "image": "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VPAP12.png",
        "qty": "1",
        "metric": "pcs",
        "currentPrice": "28",
        "benefits": "No Details Available",
        "info": "No Details Available",
        "category": "fruits"
    }
]

localStorage.setItem('products',JSON.stringify(products))